### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by randomthought** [fallenhitokiri/autocomplete-plus-jedi#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.1
**Thrown From**: [autocomplete-plus-jedi](https://github.com/fallenhitokiri/autocomplete-plus-jedi) package, v0.0.7
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/malcolmmd/.atom/packages/autocomplete-plus-jedi/lib/jedi-provider.coffee:59

TypeError: Cannot read property 'length' of undefined
  at /Users/malcolmmd/.atom/packages/autocomplete-plus-jedi/lib/jedi-provider.coffee:59:19
  at ChildProcess.exithandler (child_process.js:740:7)
  at ChildProcess.emit (events.js:119:17)
  at maybeClose (child_process.js:1013:16)
  at Socket.<anonymous> (child_process.js:1181:11)
  at Socket.emit (events.js:116:17)
  at Pipe.close (net.js:477:12)

```
### Commands

```
     -8:47.6 vim-mode:reset-command-mode (atom-text-editor.editor.mini)
     -8:45.6 vim-mode:activate-insert-mode (atom-text-editor.editor.mini)
     -8:35.3 autocomplete-jedi:toggle (atom-text-editor.editor.mini)
     -8:33.4 vim-mode:delete-right (atom-text-editor.editor.vim-mode.command-mode)
     -8:31.1 vim-mode:move-to-last-character-of-line (atom-text-editor.editor.vim-mode.command-mode)
     -8:29.5 vim-mode:insert-after (atom-text-editor.editor.vim-mode.command-mode)
     -8:28.1 core:backspace (atom-text-editor.editor.vim-mode.command-mode)
     -8:25.6 autocomplete-jedi:toggle (atom-text-editor.editor.vim-mode.command-mode)
     -8:23.9 editor:consolidate-selections (atom-text-editor.editor.mini)
     -8:23.9 vim-mode:activate-command-mode (atom-text-editor.editor.mini)
  2x -8:21.4 vim-mode:delete (atom-text-editor.editor.mini)
     -8:01.3 core:confirm (atom-text-editor.editor.mini)
     -0:04.7 vim-mode:insert-after (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:04.1 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:02.8 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:02.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "spacegray-dark-syntax"
    ],
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v2.6.0
autocomplete-plus, v2.4.0
autocomplete-plus-jedi, v0.0.7
file-icons, v1.5.0
ide-haskell, v0.3.5
language-haskell, v1.0.0
language-scala, v1.1.0
linter, v0.12.0
linter-clang, v2.25.1
linter-javac, v0.1.3
linter-pylama, v0.0.15
linter-scalac, v0.3.3
minimap, v4.5.0
script, v2.18.0
set-syntax, v0.2.1
spacegray-dark-syntax, v0.2.0
vim-mode, v0.35.0

# Dev
No dev packages
```

**Comment by randomthought** [comment]
Hello,
I'm new to Atom. I hope I'm doing things right. 
Anyway, the code complete looks to be working. But I keep getting that error every time I type a letter.

**Comment by randomthought** [comment]
It seems to be a conflict with the ide-haskell, v0.3.5 plugin. It worked fine after I disabled the plugin.

**Comment by fallenhitokiri** [comment]
I will take a look at the ide-Haskell plugin after doing the next release this week.

Eventually registering the jedi plugin as only provider for Pyhton is sufficient (depending on what the actual problem is), so the new release could already fix this.

Thanks for the detailed information!

**Comment by fallenhitokiri** [comment]
0.0.8 was just published - if I reproduced your setup correctly this should solve the problem. Please let me know

**Comment by randomthought** [comment]
Issue is still present. It's okay, I can disable ide-haskell. I don't use it as often. Thanks a lot for writing this. Once I become familiar with coffee script, I will see if I can help fix the issue.

**Comment by fallenhitokiri** [comment]
as discussed here we try to consolidate all jedi providers - therefore this repo will be closed. https://github.com/tinloaf/autocomplete-plus-python-jedi/issues/16
